sudo: required
services:
  - docker

before_install:
  - docker build -t vinniiee/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true vinniiee/react-test npm run test

after_success:
  - docker build -t vinniiee/multi-client ./client
  - docker build -t vinniiee/multi-worker ./worker
  - docker build -t vinniiee/multi-server ./server
  - docker build -t vinniiee/multi-nginx ./nginx

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  - docker push vinniiee/multi-client
  - docker push vinniiee/multi-worker
  - docker push vinniiee/multi-server
  - docker push vinniiee/multi-nginx
